stages:
  - test
variables:
  GIT_SSL_NO_VERIFY: "true"
Test:
  stage: test
  script:
    - . .\Tests\PesterPrep.ps1 
    - Invoke-Pester -EnableExit -Script .\Tests\*.Tests.ps1
  tags: 
    - PowerShell